
services:
  database:
    image: postgres
    environment:
      POSTGRES_PASSWORD: secretpassword
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      database:
        ipv4_address: 192.168.69.69
        
  backend:
    build:
      context: ./backend
    environment:
      POSTGRES_HOST: 192.168.69.69
    networks:
      - database
      
networks:
  database:
    ipam:
      driver: default
      config:
        - subnet: "192.168.69.0/24"

volumes:
  postgres-data:
  
