
services:
  backend:
    ports:
      - 3001:3001
    volumes:
      - ./backend/pkg:/app/pkg
      
  frontend:
    build: ./frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend/src:/app/src
      
