FROM node:alpine AS frontend

WORKDIR /app

COPY frontend/package.json . 
RUN npm install 

COPY frontend/ .
RUN npm run build

FROM golang:alpine

WORKDIR /app

COPY --from=frontend /app/dist/ public/

COPY backend/go.mod .
COPY backend/go.sum .

RUN go mod download

COPY backend/ .
RUN go build -o bin

ENTRYPOINT [ "./bin" ]
